import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateProductSubscriptionTable1781501705435 implements MigrationInterface {
  name = 'CreateProductSubscriptionTable1781501705435';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "subscriptions" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "TITLE" varchar2(150) NOT NULL, "DESCRIPTION" clob NOT NULL, "IS_SHOW" number DEFAULT 1 NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "DELETED_AT" timestamp, CONSTRAINT "PK_01cc21315a32871c063b798ff62" PRIMARY KEY ("ID"))`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "subscriptions"`);
  }
}
