import { MigrationInterface, QueryRunner } from 'typeorm';

export class Updatealltable1781627627586 implements MigrationInterface {
  name = 'Updatealltable1781627627586';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "ORDER_ITEM" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "QUANTITY" number NOT NULL, "DISSCOUNT" number NOT NULL, "ADDON_PRODUCT" clob NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "DELETED_AT" timestamp, "PRODUCT_ID" number, "PRODUCT_VARIANT_ID" number, "ORDER_ID" number, "STORE_ID" number, CONSTRAINT "REL_43753526d133eff3026a384eca" UNIQUE ("PRODUCT_ID"), CONSTRAINT "REL_6e1302dd72772d4d3672e2eb73" UNIQUE ("PRODUCT_VARIANT_ID"), CONSTRAINT "REL_83568506245a6ee3249c0823bf" UNIQUE ("ORDER_ID"), CONSTRAINT "REL_ca60b440157c8adc7cdb3b5348" UNIQUE ("STORE_ID"), CONSTRAINT "PK_64737fe3beed0b292a025a9a70d" PRIMARY KEY ("ID"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "STORE" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "NAME" varchar2(150) NOT NULL, "ADDRESS" clob NOT NULL, "TYPE" varchar2(150) NOT NULL, "DESCRIPTION" clob NOT NULL, "RATING" number(1,1) DEFAULT 0, "CITY" varchar2(200) NOT NULL, "DATEONLINELAST" date, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "DELETED_AT" timestamp, "SELLER_ID" number, CONSTRAINT "REL_06291a8ed65794a3a7e3e448b9" UNIQUE ("SELLER_ID"), CONSTRAINT "PK_1871e228407a7559bb8f987e215" PRIMARY KEY ("ID"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "ADDRESS" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "NAMA_PENERIMA" varchar2(150) NOT NULL, "NO_HP" varchar2(50) NOT NULL, "ADDRESS" blob NOT NULL, "NOTE" blob NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "DELETED_AT" timestamp, CONSTRAINT "PK_64ef9f7295ce00f6475ae8c1fdc" PRIMARY KEY ("ID"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "PROFILE" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "BIRTH_PLACE" varchar2(255) NOT NULL, "BIRTH_DATE" date NOT NULL, "GENDER" varchar2(50) NOT NULL, "NO_HP" varchar2(50) NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "DELETED_AT" timestamp, CONSTRAINT "PK_1b287be40975f343689f529fa65" PRIMARY KEY ("ID"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "PRODUCT_CATEGORIES" ADD "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "PRODUCT_CATEGORIES" ADD "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "PRODUCT_CATEGORIES" ADD "DELETED_AT" timestamp`,
    );
    await queryRunner.query(
      `ALTER TABLE "USER_SUBSCRIPTION" ADD "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "USER_SUBSCRIPTION" ADD "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "USER_SUBSCRIPTION" ADD "DELETED_AT" timestamp`,
    );
    await queryRunner.query(
      `ALTER TABLE "PRODUCT_IMAGE" ADD CONSTRAINT "FK_fab5f4dd5075b7dd7e5e029404f" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "PRODUCT_IMAGE" ADD CONSTRAINT "FK_a6c1dac4ba5ebe8c3f9a9b941c4" FOREIGN KEY ("PRODUCT_VARIANT_ID") REFERENCES "PRODUCT_VARIANT" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "PRODUCT_IMAGE" ADD CONSTRAINT "FK_8831619cf1f483a7b6dee5fe2c8" FOREIGN KEY ("ADD_PRODUCT_ID") REFERENCES "ADDON_PRODUCT" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "DISCOUNT_USAGE" ADD CONSTRAINT "FK_00818e23468a128e31cd8636672" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "DISCOUNT_USAGE" ADD CONSTRAINT "FK_abd2c0c52b9a3467eda4b93e547" FOREIGN KEY ("DISCOUNT_ID") REFERENCES "DISCOUNT" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "DISCOUNT" ADD CONSTRAINT "FK_495a5d416731c07b808636251ea" FOREIGN KEY ("STORE_ID") REFERENCES "STORE" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "DISCOUNT" ADD CONSTRAINT "FK_0643b7586e525ecc8214550ab96" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "ORDER_IMAGE_CONFIRMED" ADD CONSTRAINT "FK_ed01ab0a02653f5c7cdd397d40a" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "ORDER_IMAGE_CONFIRMED" ADD CONSTRAINT "FK_9b73b9fe176fb35b0070c7b185b" FOREIGN KEY ("ORDER_ID") REFERENCES "ORDER" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "PAYMENT_ORDER" ADD CONSTRAINT "FK_78ebc41b395a14eebe0f4125583" FOREIGN KEY ("ORDER_ID") REFERENCES "ORDER" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "ORDER_ITEM" ADD CONSTRAINT "FK_43753526d133eff3026a384ecad" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "ORDER_ITEM" ADD CONSTRAINT "FK_6e1302dd72772d4d3672e2eb739" FOREIGN KEY ("PRODUCT_VARIANT_ID") REFERENCES "PRODUCT_VARIANT" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "ORDER_ITEM" ADD CONSTRAINT "FK_83568506245a6ee3249c0823bf8" FOREIGN KEY ("ORDER_ID") REFERENCES "ORDER" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "ORDER_ITEM" ADD CONSTRAINT "FK_ca60b440157c8adc7cdb3b53484" FOREIGN KEY ("STORE_ID") REFERENCES "STORE" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "STORE" ADD CONSTRAINT "FK_06291a8ed65794a3a7e3e448b93" FOREIGN KEY ("SELLER_ID") REFERENCES "SELLER" ("ID")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "STORE" DROP CONSTRAINT "FK_06291a8ed65794a3a7e3e448b93"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ORDER_ITEM" DROP CONSTRAINT "FK_ca60b440157c8adc7cdb3b53484"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ORDER_ITEM" DROP CONSTRAINT "FK_83568506245a6ee3249c0823bf8"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ORDER_ITEM" DROP CONSTRAINT "FK_6e1302dd72772d4d3672e2eb739"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ORDER_ITEM" DROP CONSTRAINT "FK_43753526d133eff3026a384ecad"`,
    );
    await queryRunner.query(
      `ALTER TABLE "PAYMENT_ORDER" DROP CONSTRAINT "FK_78ebc41b395a14eebe0f4125583"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ORDER_IMAGE_CONFIRMED" DROP CONSTRAINT "FK_9b73b9fe176fb35b0070c7b185b"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ORDER_IMAGE_CONFIRMED" DROP CONSTRAINT "FK_ed01ab0a02653f5c7cdd397d40a"`,
    );
    await queryRunner.query(
      `ALTER TABLE "DISCOUNT" DROP CONSTRAINT "FK_0643b7586e525ecc8214550ab96"`,
    );
    await queryRunner.query(
      `ALTER TABLE "DISCOUNT" DROP CONSTRAINT "FK_495a5d416731c07b808636251ea"`,
    );
    await queryRunner.query(
      `ALTER TABLE "DISCOUNT_USAGE" DROP CONSTRAINT "FK_abd2c0c52b9a3467eda4b93e547"`,
    );
    await queryRunner.query(
      `ALTER TABLE "DISCOUNT_USAGE" DROP CONSTRAINT "FK_00818e23468a128e31cd8636672"`,
    );
    await queryRunner.query(
      `ALTER TABLE "PRODUCT_IMAGE" DROP CONSTRAINT "FK_8831619cf1f483a7b6dee5fe2c8"`,
    );
    await queryRunner.query(
      `ALTER TABLE "PRODUCT_IMAGE" DROP CONSTRAINT "FK_a6c1dac4ba5ebe8c3f9a9b941c4"`,
    );
    await queryRunner.query(
      `ALTER TABLE "PRODUCT_IMAGE" DROP CONSTRAINT "FK_fab5f4dd5075b7dd7e5e029404f"`,
    );
    await queryRunner.query(
      `ALTER TABLE "USER_SUBSCRIPTION" DROP COLUMN "DELETED_AT"`,
    );
    await queryRunner.query(
      `ALTER TABLE "USER_SUBSCRIPTION" DROP COLUMN "UPDATED_AT"`,
    );
    await queryRunner.query(
      `ALTER TABLE "USER_SUBSCRIPTION" DROP COLUMN "CREATED_AT"`,
    );
    await queryRunner.query(
      `ALTER TABLE "PRODUCT_CATEGORIES" DROP COLUMN "DELETED_AT"`,
    );
    await queryRunner.query(
      `ALTER TABLE "PRODUCT_CATEGORIES" DROP COLUMN "UPDATED_AT"`,
    );
    await queryRunner.query(
      `ALTER TABLE "PRODUCT_CATEGORIES" DROP COLUMN "CREATED_AT"`,
    );
    await queryRunner.query(`DROP TABLE "PROFILE"`);
    await queryRunner.query(`DROP TABLE "ADDRESS"`);
    await queryRunner.query(`DROP TABLE "STORE"`);
    await queryRunner.query(`DROP TABLE "ORDER_ITEM"`);
  }
}
