import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateUserTable1781272981607 implements MigrationInterface {
    name = 'CreateUserTable1781272981607'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "USERS" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "NAME" varchar2(100) NOT NULL, "USERNAME" varchar2(100) NOT NULL, "EMAIL" varchar2(150) NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "DELETED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "UQ_aee8157a892cb0a4bab4a2fc742" UNIQUE ("USERNAME"), CONSTRAINT "UQ_03c5c0bfa50dcdf69c204bdebf2" UNIQUE ("EMAIL"), CONSTRAINT "PK_475d4b511309ada89807bc2d40b" PRIMARY KEY ("ID"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "USERS"`);
    }

}
