import { MigrationInterface, QueryRunner } from 'typeorm';

export class UpdateUserTable1781489938143 implements MigrationInterface {
  name = 'UpdateUserTable1781489938143';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "ADMIN" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "NAME" varchar2(100) NOT NULL, "USERNAME" varchar2(100) NOT NULL, "EMAIL" varchar2(150) NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "DELETED_AT" timestamp, "USER_ID" number, CONSTRAINT "UQ_d2bfc4cdf88e55b670b3b31c8f6" UNIQUE ("USERNAME"), CONSTRAINT "UQ_36271dd42ec0efc5f0850edcbb5" UNIQUE ("EMAIL"), CONSTRAINT "REL_5c01b821747bd38f11d9a8d9cc" UNIQUE ("USER_ID"), CONSTRAINT "PK_6c2fabe187ac362fb75ae3cb658" PRIMARY KEY ("ID"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "USERS" MODIFY "DELETED_AT" timestamp DEFAULT NULL NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "ADMIN" ADD CONSTRAINT "FK_5c01b821747bd38f11d9a8d9cc2" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "ADMIN" DROP CONSTRAINT "FK_5c01b821747bd38f11d9a8d9cc2"`,
    );
    await queryRunner.query(
      `ALTER TABLE "USERS" MODIFY "DELETED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL`,
    );
    await queryRunner.query(`DROP TABLE "ADMIN"`);
  }
}
