import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateProductSubscriptionTable1781501566108 implements MigrationInterface {
  name = 'CreateProductSubscriptionTable1781501566108';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "subscription" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "TITLE" varchar2(150) NOT NULL, "DESCRIPTION" clob NOT NULL, "IS_SHOW" number DEFAULT 1 NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "DELETED_AT" timestamp, CONSTRAINT "PK_a20afd7dd56f8a7178512b957cd" PRIMARY KEY ("ID"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "USER_SUBSCRIPTION" ("ID" number GENERATED BY DEFAULT AS IDENTITY, CONSTRAINT "PK_72b0b278251a648a3d89bb9f7d3" PRIMARY KEY ("ID"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "SUB_PRODUCT_CATEGORIES" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "TITLE" varchar2(150) NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "DELETED_AT" timestamp, CONSTRAINT "PK_21b0455306bea069ddeaf51865e" PRIMARY KEY ("ID"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "PRODUCT_CATEGORIES" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "title" varchar2(150) NOT NULL, CONSTRAINT "PK_3449d58c1cad4ba50c83c918d43" PRIMARY KEY ("ID"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "USERS" DROP CONSTRAINT "UQ_03c5c0bfa50dcdf69c204bdebf2"`,
    );
    await queryRunner.query(`ALTER TABLE "USERS" DROP COLUMN "EMAIL"`);
    await queryRunner.query(
      `ALTER TABLE "USERS" ADD "EMAIL" varchar2(255) NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "USERS" ADD CONSTRAINT "UQ_03c5c0bfa50dcdf69c204bdebf2" UNIQUE ("EMAIL")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "USERS" DROP CONSTRAINT "UQ_03c5c0bfa50dcdf69c204bdebf2"`,
    );
    await queryRunner.query(`ALTER TABLE "USERS" DROP COLUMN "EMAIL"`);
    await queryRunner.query(
      `ALTER TABLE "USERS" ADD "EMAIL" varchar2(150) NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "USERS" ADD CONSTRAINT "UQ_03c5c0bfa50dcdf69c204bdebf2" UNIQUE ("EMAIL")`,
    );
    await queryRunner.query(`DROP TABLE "PRODUCT_CATEGORIES"`);
    await queryRunner.query(`DROP TABLE "SUB_PRODUCT_CATEGORIES"`);
    await queryRunner.query(`DROP TABLE "USER_SUBSCRIPTION"`);
    await queryRunner.query(`DROP TABLE "subscription"`);
  }
}
