import { MigrationInterface, QueryRunner } from 'typeorm';

export class Updatealltable1781664496161 implements MigrationInterface {
  name = 'Updatealltable1781664496161';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "PRODUCT_IMAGE" DROP CONSTRAINT "FK_8831619cf1f483a7b6dee5fe2c8"`,
    );
    await queryRunner.query(
      `ALTER TABLE "PRODUCT_IMAGE" RENAME COLUMN "ADD_PRODUCT_ID" TO "ADDON_PRODUCT_ID"`,
    );
    await queryRunner.query(
      `CREATE TABLE "REVIEW_IMAGE" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "IMAGE_URL" varchar2(255) NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "DELETED_AT" timestamp, "REVIEW_ID" number, CONSTRAINT "REL_03f074bc14bb2be22ad48732a6" UNIQUE ("REVIEW_ID"), CONSTRAINT "PK_5d81929bee8071ba8729eebe28c" PRIMARY KEY ("ID"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "REVIEW" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "RATING" number NOT NULL, "COMMENT" clob NOT NULL, "IS_ANONYMOUS" number DEFAULT 0 NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "DELETED_AT" timestamp, "USER_ID" number, "PRODUCT_ID" number, "ORDER_ID" number, CONSTRAINT "REL_bb660627ed3a411fc3360509ba" UNIQUE ("USER_ID"), CONSTRAINT "REL_0a511d070efd186109887cdf20" UNIQUE ("PRODUCT_ID"), CONSTRAINT "REL_a0b17dfdde3ee1b6a66ce60228" UNIQUE ("ORDER_ID"), CONSTRAINT "PK_ca0fdd1f373a7b915018982f40b" PRIMARY KEY ("ID"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "PRODUCT_IMAGE" ADD CONSTRAINT "FK_9bd5b08e8a78db7cfc560d6f6fd" FOREIGN KEY ("ADDON_PRODUCT_ID") REFERENCES "ADDON_PRODUCT" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "REVIEW_IMAGE" ADD CONSTRAINT "FK_03f074bc14bb2be22ad48732a6e" FOREIGN KEY ("REVIEW_ID") REFERENCES "REVIEW" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_bb660627ed3a411fc3360509ba4" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_0a511d070efd186109887cdf204" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_a0b17dfdde3ee1b6a66ce602282" FOREIGN KEY ("ORDER_ID") REFERENCES "ORDER" ("ID")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "REVIEW" DROP CONSTRAINT "FK_a0b17dfdde3ee1b6a66ce602282"`,
    );
    await queryRunner.query(
      `ALTER TABLE "REVIEW" DROP CONSTRAINT "FK_0a511d070efd186109887cdf204"`,
    );
    await queryRunner.query(
      `ALTER TABLE "REVIEW" DROP CONSTRAINT "FK_bb660627ed3a411fc3360509ba4"`,
    );
    await queryRunner.query(
      `ALTER TABLE "REVIEW_IMAGE" DROP CONSTRAINT "FK_03f074bc14bb2be22ad48732a6e"`,
    );
    await queryRunner.query(
      `ALTER TABLE "PRODUCT_IMAGE" DROP CONSTRAINT "FK_9bd5b08e8a78db7cfc560d6f6fd"`,
    );
    await queryRunner.query(`DROP TABLE "REVIEW"`);
    await queryRunner.query(`DROP TABLE "REVIEW_IMAGE"`);
    await queryRunner.query(
      `ALTER TABLE "PRODUCT_IMAGE" RENAME COLUMN "ADDON_PRODUCT_ID" TO "ADD_PRODUCT_ID"`,
    );
    await queryRunner.query(
      `ALTER TABLE "PRODUCT_IMAGE" ADD CONSTRAINT "FK_8831619cf1f483a7b6dee5fe2c8" FOREIGN KEY ("ADD_PRODUCT_ID") REFERENCES "ADDON_PRODUCT" ("ID")`,
    );
  }
}
