import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateProductSubscriptionTable1781501747651 implements MigrationInterface {
  name = 'CreateProductSubscriptionTable1781501747651';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "SUBSCRPTIONS" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "TITLE" varchar2(150) NOT NULL, "DESCRIPTION" clob NOT NULL, "IS_SHOW" number DEFAULT 1 NOT NULL, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "DELETED_AT" timestamp, CONSTRAINT "PK_5a349a819a4234ccb418c0d8a2e" PRIMARY KEY ("ID"))`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "SUBSCRPTIONS"`);
  }
}
