import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateSellerTable1781492726905 implements MigrationInterface {
  name = 'CreateSellerTable1781492726905';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "SELLER" ("ID" number GENERATED BY DEFAULT AS IDENTITY, "CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "DELETED_AT" timestamp, "USER_ID" number, CONSTRAINT "REL_743d102b5e2c7122969dbbd2ec" UNIQUE ("USER_ID"), CONSTRAINT "PK_f38e798c33e5973bbcb01341af0" PRIMARY KEY ("ID"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "ADMIN" DROP CONSTRAINT "FK_5c01b821747bd38f11d9a8d9cc2"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ADMIN" MODIFY "USER_ID" number  NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "ADMIN" ADD CONSTRAINT "FK_5c01b821747bd38f11d9a8d9cc2" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "SELLER" ADD CONSTRAINT "FK_743d102b5e2c7122969dbbd2ecf" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "SELLER" DROP CONSTRAINT "FK_743d102b5e2c7122969dbbd2ecf"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ADMIN" DROP CONSTRAINT "FK_5c01b821747bd38f11d9a8d9cc2"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ADMIN" MODIFY "USER_ID" number  NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "ADMIN" ADD CONSTRAINT "FK_5c01b821747bd38f11d9a8d9cc2" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID")`,
    );
    await queryRunner.query(`DROP TABLE "SELLER"`);
  }
}
